from enum import Enum

class EnvironmentType(str, Enum):
    DEVELOPMENT = "DEVELOPMENT"
    STAGING = "STAGING"
    PRODUCTION = "PRODUCTION"
    OTHER = "OTHER"

class ResourceType(str, Enum):
    HOST = "HOST"
    VM = "VM"
    CONTAINER = "CONTAINER"
    SERVICE = "SERVICE"
    DATABASE = "DATABASE"
    KUBERNETES_CLUSTER = "KUBERNETES_CLUSTER"
    KUBERNETES_NODE = "KUBERNETES_NODE"
    KUBERNETES_NAMESPACE = "KUBERNETES_NAMESPACE"
    KUBERNETES_POD = "KUBERNETES_POD"
    KUBERNETES_DEPLOYMENT = "KUBERNETES_DEPLOYMENT"
    KUBERNETES_SERVICE = "KUBERNETES_SERVICE"
    KUBERNETES_REPLICA_SET = "KUBERNETES_REPLICA_SET"
    KUBERNETES_DAEMON_SET = "KUBERNETES_DAEMON_SET"
    KUBERNETES_STATEFUL_SET = "KUBERNETES_STATEFUL_SET"
    KUBERNETES_JOB = "KUBERNETES_JOB"
    KUBERNETES_CRON_JOB = "KUBERNETES_CRON_JOB"
    KUBERNETES_CONFIG_MAP = "KUBERNETES_CONFIG_MAP"
    KUBERNETES_SECRET = "KUBERNETES_SECRET"
    KUBERNETES_INGRESS = "KUBERNETES_INGRESS"
    NETWORK = "NETWORK"
    NETWORK_ENDPOINT = "NETWORK_ENDPOINT"
    LOAD_BALANCER = "LOAD_BALANCER"
    STORAGE = "STORAGE"
    CLOUD_ACCOUNT = "CLOUD_ACCOUNT"
    CLOUD_REGION = "CLOUD_REGION"
    CLOUD_INSTANCE = "CLOUD_INSTANCE"
    CLOUD_VOLUME = "CLOUD_VOLUME"
    CLOUD_NETWORK = "CLOUD_NETWORK"
    CLOUD_VPC = "CLOUD_VPC"
    CLOUD_SECURITY_GROUP = "CLOUD_SECURITY_GROUP"
    CLOUD_SUBNET = "CLOUD_SUBNET"
    CLOUD_LOAD_BALANCER = "CLOUD_LOAD_BALANCER"
    CLOUD_BUCKET = "CLOUD_BUCKET"
    CLOUD_AUTO_SCALING_GROUP = "CLOUD_AUTO_SCALING_GROUP"
    CLOUD_LAUNCH_TEMPLATE = "CLOUD_LAUNCH_TEMPLATE"
    CLOUD_ROUTE_TABLE = "CLOUD_ROUTE_TABLE"
    CLOUD_INTERNET_GATEWAY = "CLOUD_INTERNET_GATEWAY"
    CLOUD_NAT_GATEWAY = "CLOUD_NAT_GATEWAY"
    CLOUD_NETWORK_INTERFACE = "CLOUD_NETWORK_INTERFACE"
    CLOUD_VOLUME_SNAPSHOT = "CLOUD_VOLUME_SNAPSHOT"
    DATABASE_INSTANCE = "DATABASE_INSTANCE"
    DATABASE_CLUSTER = "DATABASE_CLUSTER"
    DATABASE_DATABASE = "DATABASE_DATABASE"
    CONTAINER_IMAGE = "CONTAINER_IMAGE"
    CONTAINER_NETWORK = "CONTAINER_NETWORK"
    CONTAINER_VOLUME = "CONTAINER_VOLUME"
    OBSERVABILITY_DASHBOARD = "OBSERVABILITY_DASHBOARD"
    OBSERVABILITY_ALERT_RULE = "OBSERVABILITY_ALERT_RULE"
    OBSERVABILITY_DATASOURCE = "OBSERVABILITY_DATASOURCE"
    OBSERVABILITY_FOLDER = "OBSERVABILITY_FOLDER"

class ResourceStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"
    MAINTENANCE = "MAINTENANCE"

class RelationshipType(str, Enum):
    CONTAINS = "CONTAINS"
    RUNS = "RUNS"
    DEPENDS_ON = "DEPENDS_ON"
    HOSTS = "HOSTS"
    PART_OF = "PART_OF"
    ROUTES_TO = "ROUTES_TO"
    CONNECTS_TO = "CONNECTS_TO"

# This is an enum representing recognized providers.
# It is used for standardization, but the system may technically accept strings
# if we decide not to strictly validate at the DB layer, though API layer will validate.
class ProviderType(str, Enum):
    MANUAL = "manual"
    PROMETHEUS = "prometheus"
    NAGIOS = "nagios"
    GRAFANA = "grafana"
    LOKI = "loki"
    KUBERNETES = "kubernetes"
    DOCKER = "docker"
    TERRAFORM = "terraform"
    ANSIBLE = "ansible"
    PUPPET = "puppet"
    AWS = "aws"
    TEST_PROVIDER = "test_provider"

class IntegrationStatus(str, Enum):
    CONFIGURED = "CONFIGURED"
    VALIDATING = "VALIDATING"
    HEALTHY = "HEALTHY"
    UNHEALTHY = "UNHEALTHY"
    DISABLED = "DISABLED"
    ERROR = "ERROR"

class Severity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"

class AlertStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    SUPPRESSED = "SUPPRESSED"

class IncidentStatus(str, Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    INVESTIGATING = "INVESTIGATING"
    REMEDIATION_PENDING = "REMEDIATION_PENDING"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    REMEDIATION_RUNNING = "REMEDIATION_RUNNING"
    VERIFYING = "VERIFYING"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    SUPPRESSED = "SUPPRESSED"

class IncidentPriority(str, Enum):
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"
    P4 = "P4"
    P5 = "P5"

class IncidentEventType(str, Enum):
    INCIDENT_CREATED = "INCIDENT_CREATED"
    ALERT_ATTACHED = "ALERT_ATTACHED"
    ALERT_DETACHED = "ALERT_DETACHED"
    STATUS_CHANGED = "STATUS_CHANGED"
    SEVERITY_CHANGED = "SEVERITY_CHANGED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    ASSIGNED = "ASSIGNED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    DIAGNOSIS_STARTED = "DIAGNOSIS_STARTED"
    DIAGNOSIS_COMPLETED = "DIAGNOSIS_COMPLETED"
    REMEDIATION_STARTED = "REMEDIATION_STARTED"
    REMEDIATION_COMPLETED = "REMEDIATION_COMPLETED"
    REMEDIATION_SELECTED = "REMEDIATION_SELECTED"
    PROVIDER_SELECTED = "PROVIDER_SELECTED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    AUTOMATION_STARTED = "AUTOMATION_STARTED"
    AUTOMATION_COMPLETED = "AUTOMATION_COMPLETED"
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
    INCIDENT_RECOVERED = "INCIDENT_RECOVERED"
    REMEDIATION_FAILED = "REMEDIATION_FAILED"
    INCIDENT_ESCALATED = "INCIDENT_ESCALATED"
    INCIDENT_RESOLVED = "INCIDENT_RESOLVED"
    INCIDENT_CLOSED = "INCIDENT_CLOSED"

class RawEventProcessingStatus(str, Enum):
    RECEIVED = "RECEIVED"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"
    DUPLICATE = "DUPLICATE"

class FailedEventStatus(str, Enum):
    FAILED = "FAILED"
    RETRYING = "RETRYING"
    QUARANTINED = "QUARANTINED"
    REPROCESSED = "REPROCESSED"
    RESOLVED = "RESOLVED"

# Phase 1.10 Automation Enums
class PlaybookStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    DEPRECATED = "DEPRECATED"

class PlaybookTriggerType(str, Enum):
    MANUAL = "MANUAL"
    INCIDENT = "INCIDENT"
    ALERT = "ALERT"
    SCHEDULED = "SCHEDULED"

class AutomationActionType(str, Enum):
    NOOP = "NOOP"
    COLLECT_INFORMATION = "COLLECT_INFORMATION"
    VALIDATE_RESOURCE = "VALIDATE_RESOURCE"
    EXECUTE_PROVIDER_ACTION = "EXECUTE_PROVIDER_ACTION"
    WAIT = "WAIT"
    VERIFY = "VERIFY"

class AutomationExecutionStatus(str, Enum):
    PENDING = "PENDING"
    POLICY_EVALUATION = "POLICY_EVALUATION"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    RUNNING = "RUNNING"
    VERIFYING = "VERIFYING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    TIMED_OUT = "TIMED_OUT"

class AutomationStepStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"

class PolicyDecisionType(str, Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"

class VerificationStatus(str, Enum):
    PENDING = "PENDING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"

class WorkflowExecutionStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"
    CANCELLED = "CANCELLED"
    TIMED_OUT = "TIMED_OUT"
    RETRYING = "RETRYING"
    DEAD_LETTERED = "DEAD_LETTERED"

class WorkflowStepStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    TIMED_OUT = "TIMED_OUT"

class ProviderErrorClassification(str, Enum):
    AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
    AUTHORIZATION_FAILURE = "AUTHORIZATION_FAILURE"
    CONNECTION_FAILURE = "CONNECTION_FAILURE"
    TIMEOUT = "TIMEOUT"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_CONFLICT = "RESOURCE_CONFLICT"
    VALIDATION_FAILURE = "VALIDATION_FAILURE"
    RATE_LIMITED = "RATE_LIMITED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    EXECUTION_FAILURE = "EXECUTION_FAILURE"
    VERIFICATION_FAILURE = "VERIFICATION_FAILURE"
    UNKNOWN_FAILURE = "UNKNOWN_FAILURE"

