"""rbac

Revision ID: 0003_rbac
Revises: 0002_identity
Create Date: 2026-09-21 16:00:00.000000

"""
from typing import Sequence, Union
import uuid
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003_rbac'
down_revision: Union[str, None] = '0002_identity'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    permissions_table = op.create_table('permissions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    
    roles_table = op.create_table('roles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    
    role_permissions_table = op.create_table('role_permissions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('permission_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('role_id', 'permission_id', name='uix_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    
    user_roles_table = op.create_table('user_roles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'role_id', name='uix_user_role')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # --- Seed data ---
    now = datetime.now(timezone.utc)
    
    # 1. Seed Permissions
    permissions = [
        "users:read", "users:manage",
        "roles:read", "roles:manage",
        "infrastructure:read", "infrastructure:manage",
        "monitoring:read", "monitoring:manage",
        "incidents:read", "incidents:manage",
        "automation:read", "automation:execute",
        "deployments:read", "deployments:manage",
        "security:read", "security:manage",
        "settings:read", "settings:manage"
    ]
    
    perm_records = []
    perm_map = {}
    for p in permissions:
        pid = uuid.uuid4()
        perm_map[p] = pid
        perm_records.append({
            "id": pid,
            "name": p,
            "description": f"Permission to {p.split(':')[1]} {p.split(':')[0]}",
            "created_at": now
        })
        
    op.bulk_insert(permissions_table, perm_records)
    
    # 2. Seed Roles
    admin_id = uuid.uuid4()
    operator_id = uuid.uuid4()
    viewer_id = uuid.uuid4()
    
    op.bulk_insert(roles_table, [
        {"id": admin_id, "name": "ADMIN", "description": "Broad platform administration", "created_at": now, "updated_at": now},
        {"id": operator_id, "name": "OPERATOR", "description": "Operational infrastructure access", "created_at": now, "updated_at": now},
        {"id": viewer_id, "name": "VIEWER", "description": "Read-only operational visibility", "created_at": now, "updated_at": now},
    ])
    
    # 3. Seed Role-Permissions
    rp_records = []
    
    # ADMIN gets all permissions
    for p_id in perm_map.values():
        rp_records.append({
            "id": uuid.uuid4(),
            "role_id": admin_id,
            "permission_id": p_id,
            "created_at": now
        })
        
    # OPERATOR gets all read permissions + specific manage/execute
    operator_perms = [
        "users:read", "roles:read", 
        "infrastructure:read", "infrastructure:manage",
        "monitoring:read", "monitoring:manage",
        "incidents:read", "incidents:manage",
        "automation:read", "automation:execute",
        "deployments:read", "deployments:manage",
        "security:read", "settings:read"
    ]
    for p in operator_perms:
        rp_records.append({
            "id": uuid.uuid4(),
            "role_id": operator_id,
            "permission_id": perm_map[p],
            "created_at": now
        })
        
    # VIEWER gets all read permissions only
    viewer_perms = [p for p in permissions if p.endswith(":read")]
    for p in viewer_perms:
        rp_records.append({
            "id": uuid.uuid4(),
            "role_id": viewer_id,
            "permission_id": perm_map[p],
            "created_at": now
        })
        
    op.bulk_insert(role_permissions_table, rp_records)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
