"""inventory

Revision ID: 1f273fed12a8
Revises: 0004_audit
Create Date: 2026-09-21 16:51:52.468555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid
from datetime import datetime, timezone

# revision identifiers, used by Alembic.
revision: str = '1f273fed12a8'
down_revision: Union[str, None] = '0004_audit'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('environment_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_name'), 'environments', ['name'], unique=True)
    op.create_table('infrastructure_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uix_provider_external_id')
    )
    op.create_index(op.f('ix_infrastructure_resources_environment_id'), 'infrastructure_resources', ['environment_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_resources_external_id'), 'infrastructure_resources', ['external_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_resources_provider'), 'infrastructure_resources', ['provider'], unique=False)
    op.create_index(op.f('ix_infrastructure_resources_resource_type'), 'infrastructure_resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_infrastructure_resources_status'), 'infrastructure_resources', ['status'], unique=False)
    op.create_table('resource_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_resource_id', sa.UUID(), nullable=False),
    sa.Column('target_resource_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_resource_id'], ['infrastructure_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_resource_id'], ['infrastructure_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_resource_id', 'target_resource_id', 'relationship_type', name='uix_resource_relationship')
    )
    op.create_index(op.f('ix_resource_relationships_relationship_type'), 'resource_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_resource_relationships_source_resource_id'), 'resource_relationships', ['source_resource_id'], unique=False)
    op.create_index(op.f('ix_resource_relationships_target_resource_id'), 'resource_relationships', ['target_resource_id'], unique=False)
    # ### end Alembic commands ###

    # --- Seed Inventory Permissions ---
    now = datetime.now(timezone.utc)
    
    permissions = [
        "resources:read", "resources:create", "resources:update",
        "environments:read", "environments:create", "environments:update",
        "relationships:read", "relationships:create"
    ]
    
    perm_records = []
    perm_map = {}
    for p in permissions:
        pid = uuid.uuid4()
        perm_map[p] = pid
        perm_records.append({
            "id": pid,
            "name": p,
            "description": f"Permission to {p.split(':')[1]} {p.split(':')[0]}",
            "created_at": now
        })
        
    permissions_table = sa.table('permissions',
        sa.column('id', sa.UUID),
        sa.column('name', sa.String),
        sa.column('description', sa.String),
        sa.column('created_at', sa.DateTime)
    )
    op.bulk_insert(permissions_table, perm_records)

    # --- Assign to existing roles ---
    connection = op.get_bind()
    
    admin_role_id = connection.execute(sa.text("SELECT id FROM roles WHERE name='ADMIN'")).scalar()
    operator_role_id = connection.execute(sa.text("SELECT id FROM roles WHERE name='OPERATOR'")).scalar()
    viewer_role_id = connection.execute(sa.text("SELECT id FROM roles WHERE name='VIEWER'")).scalar()
    
    role_permissions_table = sa.table('role_permissions',
        sa.column('id', sa.UUID),
        sa.column('role_id', sa.UUID),
        sa.column('permission_id', sa.UUID),
        sa.column('created_at', sa.DateTime)
    )
    
    rp_records = []
    
    # ADMIN gets all
    if admin_role_id:
        for p_id in perm_map.values():
            rp_records.append({
                "id": uuid.uuid4(),
                "role_id": admin_role_id,
                "permission_id": p_id,
                "created_at": now
            })
            
    # OPERATOR gets all in this phase since they manage infrastructure
    if operator_role_id:
        for p_id in perm_map.values():
            rp_records.append({
                "id": uuid.uuid4(),
                "role_id": operator_role_id,
                "permission_id": p_id,
                "created_at": now
            })
            
    # VIEWER gets read only
    if viewer_role_id:
        viewer_perms = [p for p in permissions if p.endswith(":read")]
        for p in viewer_perms:
            rp_records.append({
                "id": uuid.uuid4(),
                "role_id": viewer_role_id,
                "permission_id": perm_map[p],
                "created_at": now
            })
            
    if rp_records:
        op.bulk_insert(role_permissions_table, rp_records)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_relationships_target_resource_id'), table_name='resource_relationships')
    op.drop_index(op.f('ix_resource_relationships_source_resource_id'), table_name='resource_relationships')
    op.drop_index(op.f('ix_resource_relationships_relationship_type'), table_name='resource_relationships')
    op.drop_table('resource_relationships')
    op.drop_index(op.f('ix_infrastructure_resources_status'), table_name='infrastructure_resources')
    op.drop_index(op.f('ix_infrastructure_resources_resource_type'), table_name='infrastructure_resources')
    op.drop_index(op.f('ix_infrastructure_resources_provider'), table_name='infrastructure_resources')
    op.drop_index(op.f('ix_infrastructure_resources_external_id'), table_name='infrastructure_resources')
    op.drop_index(op.f('ix_infrastructure_resources_environment_id'), table_name='infrastructure_resources')
    op.drop_table('infrastructure_resources')
    op.drop_index(op.f('ix_environments_name'), table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###

    # --- Downgrade Permissions ---
    connection = op.get_bind()
    connection.execute(sa.text(
        "DELETE FROM permissions WHERE name IN ("
        "'resources:read', 'resources:create', 'resources:update', "
        "'environments:read', 'environments:create', 'environments:update', "
        "'relationships:read', 'relationships:create'"
        ")"
    ))
