"""integrations

Revision ID: cb81d0af2dc3
Revises: 1f273fed12a8
Create Date: 2026-09-21 17:21:56.082969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb81d0af2dc3'
down_revision: Union[str, None] = '1f273fed12a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_payload', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed RBAC permissions
    op.execute(
        """
        INSERT INTO permissions (id, name, description, created_at) VALUES
        (gen_random_uuid(), 'integrations:read', 'Read integrations', NOW()),
        (gen_random_uuid(), 'integrations:create', 'Create integrations', NOW()),
        (gen_random_uuid(), 'integrations:update', 'Update integrations', NOW()),
        (gen_random_uuid(), 'integrations:validate', 'Validate integrations', NOW()),
        (gen_random_uuid(), 'integrations:enable', 'Enable integrations', NOW()),
        (gen_random_uuid(), 'integrations:disable', 'Disable integrations', NOW()),
        (gen_random_uuid(), 'integrations:discover', 'Discover integration resources', NOW());

        -- Assign permissions to roles
        WITH perms AS (SELECT id, name FROM permissions WHERE name LIKE 'integrations:%'),
             viewer AS (SELECT id FROM roles WHERE name = 'VIEWER'),
             operator AS (SELECT id FROM roles WHERE name = 'OPERATOR'),
             admin AS (SELECT id FROM roles WHERE name = 'ADMIN')
        INSERT INTO role_permissions (id, role_id, permission_id, created_at)
        SELECT gen_random_uuid(), viewer.id, perms.id, NOW() FROM viewer, perms WHERE perms.name IN ('integrations:read')
        UNION ALL
        SELECT gen_random_uuid(), operator.id, perms.id, NOW() FROM operator, perms WHERE perms.name IN ('integrations:read', 'integrations:validate', 'integrations:discover')
        UNION ALL
        SELECT gen_random_uuid(), admin.id, perms.id, NOW() FROM admin, perms;
        """
    )


def downgrade() -> None:
    # Remove RBAC permissions
    op.execute("DELETE FROM permissions WHERE name LIKE 'integrations:%';")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integrations')
    # ### end Alembic commands ###
