"""events_and_incidents

Revision ID: 778a6d9f28eb
Revises: cb81d0af2dc3
Create Date: 2026-09-22 08:35:37.408934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
import uuid

def _insert_permissions(connection):
    permissions_table = sa.table(
        'permissions',
        sa.column('id', sa.UUID),
        sa.column('name', sa.String),
        sa.column('description', sa.String)
    )
    
    permissions = [
        {"id": uuid.uuid4(), "name": "events:read", "description": "Read raw events"},
        {"id": uuid.uuid4(), "name": "events:ingest", "description": "Ingest raw events"},
        {"id": uuid.uuid4(), "name": "alerts:read", "description": "Read normalized alerts"},
        {"id": uuid.uuid4(), "name": "alerts:update", "description": "Update/Acknowledge/Resolve alerts"},
        {"id": uuid.uuid4(), "name": "incidents:read", "description": "Read incidents"},
        {"id": uuid.uuid4(), "name": "incidents:update", "description": "Update/Acknowledge/Resolve incidents"},
        {"id": uuid.uuid4(), "name": "incidents:manage", "description": "Manage incidents completely"},
    ]
    
    connection.execute(permissions_table.insert().values(permissions))
    
    # Assign permissions to roles
    roles_table = sa.table('roles', sa.column('id', sa.UUID), sa.column('name', sa.String))
    role_perms_table = sa.table('role_permissions', sa.column('role_id', sa.UUID), sa.column('permission_id', sa.UUID))
    
    roles = connection.execute(sa.select(roles_table.c.id, roles_table.c.name)).fetchall()
    role_map = {name: id for id, name in roles}
    
    role_permissions = []
    for perm in permissions:
        # Admin gets everything
        if "admin" in role_map:
            role_permissions.append({"role_id": role_map["admin"], "permission_id": perm["id"]})
        
        # Viewer gets read
        if "viewer" in role_map and perm["name"].endswith(":read"):
            role_permissions.append({"role_id": role_map["viewer"], "permission_id": perm["id"]})
            
        # Operator gets read and update (no ingest, no manage)
        if "operator" in role_map and (perm["name"].endswith(":read") or perm["name"].endswith(":update")):
            role_permissions.append({"role_id": role_map["operator"], "permission_id": perm["id"]})
            
    if role_permissions:
        connection.execute(role_perms_table.insert().values(role_permissions))

def _delete_permissions(connection):
    connection.execute(sa.text("DELETE FROM permissions WHERE name LIKE 'events:%' OR name LIKE 'alerts:%' OR name LIKE 'incidents:%'"))

revision: str = '778a6d9f28eb'
down_revision: Union[str, None] = 'cb81d0af2dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('primary_resource_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('correlation_key', sa.String(length=255), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_resource_id'], ['infrastructure_resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_correlation_key'), 'incidents', ['correlation_key'], unique=False)
    op.create_index(op.f('ix_incidents_opened_at'), 'incidents', ['opened_at'], unique=False)
    op.create_index(op.f('ix_incidents_primary_resource_id'), 'incidents', ['primary_resource_id'], unique=False)
    op.create_index(op.f('ix_incidents_priority'), 'incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_incidents_resolved_at'), 'incidents', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('raw_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('resource_external_id', sa.String(length=255), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['infrastructure_resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_events_payload_hash'), 'raw_events', ['payload_hash'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_event_id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['infrastructure_resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_fingerprint'), 'alerts', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_alerts_raw_event_id'), 'alerts', ['raw_event_id'], unique=False)
    op.create_index(op.f('ix_alerts_resource_id'), 'alerts', ['resource_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_starts_at'), 'alerts', ['starts_at'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_created_at'), 'incident_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    
    # Seed new RBAC permissions
    _insert_permissions(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_created_at'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_starts_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_resource_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_raw_event_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_fingerprint'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_raw_events_payload_hash'), table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_resolved_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_priority'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_primary_resource_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_opened_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_correlation_key'), table_name='incidents')
    op.drop_table('incidents')
    
    # Remove seeded RBAC permissions
    _delete_permissions(op.get_bind())
    # ### end Alembic commands ###
