"""phase_1_10_automation

Revision ID: 106dc4736f4d
Revises: d4fe95899dbf
Create Date: 2026-09-22 17:52:39.802236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106dc4736f4d'
down_revision: Union[str, None] = 'd4fe95899dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbooks_id'), 'playbooks', ['id'], unique=False)
    op.create_index(op.f('ix_playbooks_name'), 'playbooks', ['name'], unique=True)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_name'), 'policies', ['name'], unique=True)
    op.create_table('playbook_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('action_name', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('continue_on_failure', sa.Boolean(), nullable=False),
    sa.Column('verification_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbook_steps_id'), 'playbook_steps', ['id'], unique=False)
    op.create_table('policy_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('expected_value', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rules_id'), 'policy_rules', ['id'], unique=False)
    op.create_table('automation_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playbook_id', sa.UUID(), nullable=False),
    sa.Column('playbook_version', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_source', sa.String(length=255), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['infrastructure_resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_executions_id'), 'automation_executions', ['id'], unique=False)
    op.create_table('automation_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['automation_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_approvals_id'), 'automation_approvals', ['id'], unique=False)
    op.create_table('automation_step_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('playbook_step_id', sa.UUID(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['automation_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playbook_step_id'], ['playbook_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_step_executions_id'), 'automation_step_executions', ['id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['automation_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    op.create_index(op.f('ix_policy_decisions_id'), 'policy_decisions', ['id'], unique=False)
    op.create_table('verification_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('step_execution_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expected_state', sa.JSON(), nullable=True),
    sa.Column('observed_state', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['automation_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_execution_id'], ['automation_step_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_id'), 'verification_results', ['id'], unique=False)

    # Insert Phase 1.10 RBAC permissions
    op.execute("""
    INSERT INTO permissions (id, name, description, created_at) VALUES 
    (gen_random_uuid(), 'playbooks:read', 'Read playbooks', NOW()),
    (gen_random_uuid(), 'playbooks:create', 'Create playbooks', NOW()),
    (gen_random_uuid(), 'playbooks:update', 'Update playbooks', NOW()),
    (gen_random_uuid(), 'playbooks:manage', 'Manage playbooks', NOW()),
    (gen_random_uuid(), 'automation:read', 'Read automations', NOW()),
    (gen_random_uuid(), 'automation:create', 'Create automations', NOW()),
    (gen_random_uuid(), 'automation:execute', 'Execute automations', NOW()),
    (gen_random_uuid(), 'automation:cancel', 'Cancel automations', NOW()),
    (gen_random_uuid(), 'automation:approve', 'Approve automations', NOW()),
    (gen_random_uuid(), 'policies:read', 'Read policies', NOW()),
    (gen_random_uuid(), 'policies:create', 'Create policies', NOW()),
    (gen_random_uuid(), 'policies:update', 'Update policies', NOW()),
    (gen_random_uuid(), 'policies:manage', 'Manage policies', NOW())
    ON CONFLICT (name) DO NOTHING;
    """)

    # Grant new permissions to ADMIN role
    op.execute("""
    INSERT INTO role_permissions (id, role_id, permission_id, created_at)
    SELECT gen_random_uuid(), r.id, p.id, NOW()
    FROM roles r CROSS JOIN permissions p
    WHERE r.name = 'ADMIN' 
    AND p.name IN (
        'playbooks:read', 'playbooks:create', 'playbooks:update', 'playbooks:manage',
        'automation:read', 'automation:create', 'automation:execute', 'automation:cancel', 'automation:approve',
        'policies:read', 'policies:create', 'policies:update', 'policies:manage'
    )
    ON CONFLICT DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_results_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_policy_decisions_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_automation_step_executions_id'), table_name='automation_step_executions')
    op.drop_table('automation_step_executions')
    op.drop_index(op.f('ix_automation_approvals_id'), table_name='automation_approvals')
    op.drop_table('automation_approvals')
    op.drop_index(op.f('ix_automation_executions_id'), table_name='automation_executions')
    op.drop_table('automation_executions')
    op.drop_index(op.f('ix_policy_rules_id'), table_name='policy_rules')
    op.drop_table('policy_rules')
    op.drop_index(op.f('ix_playbook_steps_id'), table_name='playbook_steps')
    op.drop_table('playbook_steps')
    op.drop_index(op.f('ix_policies_name'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_playbooks_name'), table_name='playbooks')
    op.drop_index(op.f('ix_playbooks_id'), table_name='playbooks')
    op.drop_table('playbooks')

    # Remove Phase 1.10 RBAC permissions
    op.execute("""
    DELETE FROM permissions WHERE name IN (
        'playbooks:read', 'playbooks:create', 'playbooks:update', 'playbooks:manage',
        'automation:read', 'automation:create', 'automation:execute', 'automation:cancel', 'automation:approve',
        'policies:read', 'policies:create', 'policies:update', 'policies:manage'
    );
    """)
    # ### end Alembic commands ###
