"""add resource scope

Revision ID: 7b9c9f2824da
Revises: 5c9a72b0c1d2
Create Date: 2026-09-24 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b9c9f2824da'
down_revision: Union[str, None] = '5c9a72b0c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_scopes_id'), 'resource_scopes', ['id'], unique=False)
    
    op.create_table('user_role_scopes',
    sa.Column('user_role_id', sa.UUID(), nullable=False),
    sa.Column('resource_scope_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resource_scope_id'], ['resource_scopes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_role_id', 'resource_scope_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_scopes')
    op.drop_index(op.f('ix_resource_scopes_id'), table_name='resource_scopes')
    op.drop_table('resource_scopes')
    # ### end Alembic commands ###
