"""Add Applications

Revision ID: c4c5e11e1625
Revises: 7b9c9f2824da
Create Date: 2026-09-25 12:07:01.183455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c5e11e1625'
down_revision: Union[str, None] = '7b9c9f2824da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_tenant_id'), 'applications', ['tenant_id'], unique=False)
    op.add_column('infrastructure_resources', sa.Column('application_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_infrastructure_resources_application_id'), 'infrastructure_resources', ['application_id'], unique=False)
    op.create_foreign_key(None, 'infrastructure_resources', 'applications', ['application_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'infrastructure_resources', type_='foreignkey')
    op.drop_index(op.f('ix_infrastructure_resources_application_id'), table_name='infrastructure_resources')
    op.drop_column('infrastructure_resources', 'application_id')
    op.drop_index(op.f('ix_applications_tenant_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
