"""phase 1_9 actual

Revision ID: d4fe95899dbf
Revises: 778a6d9f28eb
Create Date: 2026-09-22 16:49:37.308138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4fe95899dbf'
down_revision: Union[str, None] = '778a6d9f28eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_event_id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('failure_type', sa.String(length=100), nullable=False),
    sa.Column('failure_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('payload_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('first_failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_events_raw_event_id'), 'failed_events', ['raw_event_id'], unique=False)
    op.create_index(op.f('ix_failed_events_status'), 'failed_events', ['status'], unique=False)
    op.add_column('incidents', sa.Column('incident_fingerprint', sa.String(length=255), nullable=True))
    op.add_column('incidents', sa.Column('correlation_confidence', sa.String(length=50), nullable=True))
    op.add_column('incidents', sa.Column('root_cause_candidate', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('contributing_resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('incidents', sa.Column('related_alerts', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('incidents', sa.Column('related_incidents', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('incidents', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_incidents_incident_fingerprint'), 'incidents', ['incident_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_incident_fingerprint'), table_name='incidents')
    op.drop_column('incidents', 'duration_seconds')
    op.drop_column('incidents', 'related_incidents')
    op.drop_column('incidents', 'related_alerts')
    op.drop_column('incidents', 'contributing_resources')
    op.drop_column('incidents', 'root_cause_candidate')
    op.drop_column('incidents', 'correlation_confidence')
    op.drop_column('incidents', 'incident_fingerprint')
    op.drop_index(op.f('ix_failed_events_status'), table_name='failed_events')
    op.drop_index(op.f('ix_failed_events_raw_event_id'), table_name='failed_events')
    op.drop_table('failed_events')
    # ### end Alembic commands ###
